In [1]:
# import requests
# import zipfile
# import io
import pandas as pd
import sqlite3
# from google.cloud import bigquery
# data from 1992 to 2018

In [2]:
# # url for zipped data
# url = 'https://www.fs.usda.gov/rds/archive/products/RDS-2013-0009.6/RDS-2013-0009.6_SQLITE.zip'
# # get zipped data
# response = requests.get(url, stream=True)
# z = zipfile.ZipFile(io.BytesIO(response.content))

In [3]:
# # extract necessary files
# z.extract('Data/FPA_FOD_20221014.sqlite')
# z.extract('Data/_variable_descriptions.csv')

In [4]:
# original pandas_gbq query
long_sql_aq = """
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.co_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.hap_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.no2_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.o3_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.pm10_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.pm25_frm_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.pm25_nonfrm_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.pm25_speciation_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.pressure_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.rh_and_dp_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.so2_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.temperature_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'
UNION ALL
SELECT poc,latitude,longitude,parameter_name,sample_duration,
date_local,units_of_measure,observation_count,
arithmetic_mean,county_code
FROM `bigquery-public-data.epa_historical_air_quality.wind_daily_summary`
WHERE state_code = '06' and date_local < '2019-01-01' and date_local > '1991-12-31' and datum != 'UNKNOWN' and datum != 'NAD27'


"""

long_sql_pt = """
SELECT  
    measurement_year,
    tree_county_code,latitude,longitude,elevation,
    trees_per_acre_unadjusted,
    water_on_plot_code_name,
    species_common_name,species_group_code_name,
    total_height,
    current_diameter,
    tree_status_code_name,
    invasive_sampling_status_code_name,
FROM `bigquery-public-data.usfs_fia.plot_tree`
WHERE plot_state_code = 6 AND total_height > 0
"""

In [5]:
sql_aq = """
SELECT *
FROM `california_air_trees_fires.epa_aq_ca5`
"""

sql_pt = """
SELECT *
FROM `california_air_trees_fires.usfs_fia_pt_ca2`
"""

In [6]:
# pandas gbq will auth with google account first, rerun after
aq = pd.read_gbq(sql_aq, dialect='standard', project_id='my-ds-projects', use_bqstorage_api=True)

In [7]:
aq.head()

,poc,latitude,longitude,parameter_name,sample_duration,date_local,units_of_measure,observation_count,arithmetic_mean,county_code,site_num
0,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-05-12,Knots,24,3.541667,011,1001
1,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-08-28,Knots,24,4.041667,011,1001
2,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-12,Knots,24,3.791667,011,1001
3,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-23,Knots,24,3.125000,011,1001
4,1,38.890941,-121.003373,Wind Speed - Resultant,1 HOUR,1999-08-03,Knots,24,2.750000,017,0020

In [8]:
# pandas gbq will auth with google account first, rerun after
pt = pd.read_gbq(sql_pt, dialect='standard', project_id='my-ds-projects', use_bqstorage_api=True)

In [9]:
pt.head()

,measurement_year,tree_county_code,latitude,longitude,elevation,trees_per_acre_unadjusted,water_on_plot_code_name,species_common_name,species_group_code_name,total_height,current_diameter,tree_status_code_name,invasive_sampling_status_code_name
0,2013,51,37.586124,-118.186569,10500,0.999188,None - no water sources within the accessible ...,Great Basin bristlecone pine,Other western softwoods,39,40.299999,Live tree,Invasive plant data collected on all accessibl...
1,2011,51,37.733501,-118.257523,9900,0.999188,None - no water sources within the accessible ...,limber pine,Other western softwoods,43,26.400000,Live tree,Invasive plant data collected on all accessibl...
2,2006,107,36.351498,-118.465668,10700,0.999188,Permanent streams or ponds too small to qualif...,foxtail pine,Other western softwoods,64,37.299999,Live tree,Not collecting invasive plant data
3,2006,107,36.511063,-118.471970,10900,6.018046,None - no water sources within the accessible ...,foxtail pine,Other western softwoods,29,8.900000,Live tree,Not collecting invasive plant data
4,2007,71,34.125198,-116.906303,10100,0.999188,None - no water sources within the accessible ...,limber pine,Other western softwoods,113,45.000000,Dead tree,Invasive plant data collected on all accessibl...

In [10]:
pt.columns

Index(['measurement_year', 'tree_county_code', 'latitude', 'longitude',
       'elevation', 'trees_per_acre_unadjusted', 'water_on_plot_code_name',
       'species_common_name', 'species_group_code_name', 'total_height',
       'current_diameter', 'tree_status_code_name',
       'invasive_sampling_status_code_name'],
      dtype='object')

In [11]:
# pt.pivot_table(columns='species_common_name',index=['measurement_year','tree_county_code'],
#         values=['latitude','longitude','elevation','trees_per_acre_unadjusted','water_on_plot_code_name',
#                 'species_group_code_name','total_height','current_diameter','tree_status_code_name','invasive_sampling_status_code_name']).reset_index()
# piv_pt = pt.pivot_table(columns='species_group_code_name',index=['measurement_year','tree_county_code'],
#         values=['latitude','longitude','elevation','trees_per_acre_unadjusted','water_on_plot_code_name',
#                 'total_height','current_diameter','tree_status_code_name','invasive_sampling_status_code_name']).reset_index()

In [12]:
# # california plots
# # pd.read_csv('https://apps.fs.usda.gov/fia/datamart/CSV/CA_PLOT.csv')
# cap = pd.read_csv('Data/CA_PLOT.csv')

# cap_col_idx = [x-1 for x in (
#     [1]+
#     list(range(12,15))+
#     list(range(18,23))+
#     [28,54]+
#     list(range(59,64))+
#     list(range(65,70))
#     )]

# # california trees
# # pd.read_csv('https://apps.fs.usda.gov/fia/datamart/CSV/CA_TREE.csv')
# cat = pd.read_csv('Data/CA_TREE.csv',dtype={'P2A_GRM_FLG':str,'GST_PNWRS':str})

# cat_col_idx = [x-1 for x in (
#     [2,4,7]+
#     list(range(15,19))+
#     [20,21,22,24,25]+
#     list(range(145,148))
#     )]

In [13]:
# cat.columns[cat_col_idx]

In [14]:
# cap = cap[cap.columns[cap_col_idx]]
# cat = cat[cat.columns[cat_col_idx]]
# # california trees n plots merged
# capt = pd.merge(cat,cap,'left',left_on='PLT_CN',right_on='CN').drop(columns=['PLT_CN','CN'])
# capt = capt[(capt.notnull().sum() > 0)[capt.notnull().sum() > 0].index]
# # capt

In [15]:
# capt.columns

In [16]:
conn = sqlite3.connect('Data/FPA_FOD_20221014.sqlite')

In [17]:
fire = pd.read_sql('''
                    select 
                    FIRE_YEAR,
                    DISCOVERY_DATE,
                    DISCOVERY_TIME,
                    NWCG_CAUSE_CLASSIFICATION,
                    NWCG_GENERAL_CAUSE,
                    FIRE_SIZE,
                    FIRE_SIZE_CLASS,
                    LATITUDE,
                    LONGITUDE,
                    FIPS_CODE,
                    FIPS_NAME
                    from fires where STATE = :state
                    ''',conn,params={'state':'CA'})
# fire = pd.read_sql('''
#                     select FIRE_YEAR,DISCOVERY_DATE,DISCOVERY_DOY,
#                         NWCG_CAUSE_CLASSIFICATION,NWCG_GENERAL_CAUSE,
#                         FIRE_SIZE,FIRE_SIZE_CLASS,
#                         LATITUDE,LONGITUDE
#                     from fires
#                     where STATE = :state
#                     ''',conn,params={'state':'CA'})
fire.columns = fire.columns.str.lower()

In [18]:
fire.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 251881 entries, 0 to 251880
Data columns (total 11 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   fire_year                  251881 non-null  int64
 1   discovery_date             251881 non-null  object
 2   discovery_time             206816 non-null  object
 3   nwcg_cause_classification  251881 non-null  object
 4   nwcg_general_cause         251881 non-null  object
 5   fire_size                  251881 non-null  float64
 6   fire_size_class            251881 non-null  object
 7   latitude                   251881 non-null  float64
 8   longitude                  251881 non-null  float64
 9   fips_code                  157156 non-null  object
 10  fips_name                  157156 non-null  object
dtypes: float64(3), int64(1), object(7)
memory usage: 21.1+ MB

In [19]:
fire.describe().T

,count,mean,std,min,25%,50%,75%,max
fire_year,251881.0,2006.010457,8.302032,1992.000000,1999.000000,2006.000000,2013.000000,2020.0000
fire_size,251881.0,83.082573,3039.451969,0.001000,0.100000,0.200000,1.000000,589368.0000
latitude,251881.0,37.251235,2.559057,32.537406,34.661935,37.396107,39.226593,42.4175
longitude,251881.0,-120.118132,2.130694,-124.402883,-121.680684,-120.491111,-118.345556,-114.1258

In [20]:
fire

,fire_year,discovery_date,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude,longitude,fips_code,fips_name
0,2005,2/2/2005,1300,Human,Power generation/transmission/distribution,0.10,A,40.036944,-121.005833,06063,Plumas County
1,2004,5/12/2004,0845,Natural,Natural,0.25,A,38.933056,-120.404444,06061,Placer County
2,2004,5/31/2004,1921,Human,Debris and open burning,0.10,A,38.984167,-120.735556,06017,El Dorado County
3,2004,6/28/2004,1600,Natural,Natural,0.10,A,38.559167,-119.913333,06003,Alpine County
4,2004,6/28/2004,1600,Natural,Natural,0.10,A,38.559167,-119.933056,06003,Alpine County
...,...,...,...,...,...,...,...,...,...,...,...
251876,2019,10/31/2019,2115,Missing data/not specified/undetermined,Missing data/not specified/undetermined,9999.00,G,34.337222,-119.053333,06111,Ventura County
251877,2019,5/29/2019,1900,Missing data/not specified/undetermined,Missing data/not specified/undetermined,835.00,E,35.307500,-119.964444,06079,San Luis Obispo County
251878,2019,6/25/2019,2230,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2422.00,F,37.472222,-121.249444,06099,Stanislaus County
251879,2019,9/4/2019,1446,Missing data/not specified/undetermined,Missing data/not specified/undetermined,54608.00,G,40.053250,-120.668900,06063,Plumas County
251880,2020,7/11/2020,1958,Missing data/not specified/undetermined,Missing data/not specified/undetermined,100.00,D,37.148611,-119.503056,06039,Madera County

In [21]:
# pt['lat'] = round(pt.latitude,1)
# pt['lon'] = round(pt.longitude,1)
# fire['lat'] = round(fire.latitude,1)
# fire['lon'] = round(fire.longitude,1)
pt = pt[pt['tree_county_code'].notna()].copy()
fire = fire[fire['fips_code'].notna()].copy()
fire['county_code'] = fire.fips_code.str[2:].astype(int)
fire

,fire_year,discovery_date,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude,longitude,fips_code,fips_name,county_code
0,2005,2/2/2005,1300,Human,Power generation/transmission/distribution,0.10,A,40.036944,-121.005833,06063,Plumas County,63
1,2004,5/12/2004,0845,Natural,Natural,0.25,A,38.933056,-120.404444,06061,Placer County,61
2,2004,5/31/2004,1921,Human,Debris and open burning,0.10,A,38.984167,-120.735556,06017,El Dorado County,17
3,2004,6/28/2004,1600,Natural,Natural,0.10,A,38.559167,-119.913333,06003,Alpine County,3
4,2004,6/28/2004,1600,Natural,Natural,0.10,A,38.559167,-119.933056,06003,Alpine County,3
...,...,...,...,...,...,...,...,...,...,...,...,...
251876,2019,10/31/2019,2115,Missing data/not specified/undetermined,Missing data/not specified/undetermined,9999.00,G,34.337222,-119.053333,06111,Ventura County,111
251877,2019,5/29/2019,1900,Missing data/not specified/undetermined,Missing data/not specified/undetermined,835.00,E,35.307500,-119.964444,06079,San Luis Obispo County,79
251878,2019,6/25/2019,2230,Missing data/not specified/undetermined,Missing data/not specified/undetermined,2422.00,F,37.472222,-121.249444,06099,Stanislaus County,99
251879,2019,9/4/2019,1446,Missing data/not specified/undetermined,Missing data/not specified/undetermined,54608.00,G,40.053250,-120.668900,06063,Plumas County,63
251880,2020,7/11/2020,1958,Missing data/not specified/undetermined,Missing data/not specified/undetermined,100.00,D,37.148611,-119.503056,06039,Madera County,39

In [22]:
fire.shape,pt.shape

((157156, 12), (299154, 13))

In [23]:
# fpt = pd.merge(left=fire,right=pt,how='left',left_on=['fire_year','county_code'],right_on=['measurement_year','tree_county_code'])
# fpt

In [24]:
# small_fire = fire[fire.fire_year==2018]
# small_fire

In [25]:
# small_pt = pt[pt.measurement_year==2018]
# small_pt = small_pt.dropna()
# small_pt

In [26]:
# small_fpt = pd.merge(left=small_fire,right=small_pt,how='right',left_on='county_code',right_on='tree_county_code')
# small_fpt

In [27]:
aq.date_local = aq.date_local.astype('datetime64[ns]')
aq

,poc,latitude,longitude,parameter_name,sample_duration,date_local,units_of_measure,observation_count,arithmetic_mean,county_code,site_num
0,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-05-12,Knots,24,3.541667,011,1001
1,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-08-28,Knots,24,4.041667,011,1001
2,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-12,Knots,24,3.791667,011,1001
3,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-23,Knots,24,3.125000,011,1001
4,1,38.890941,-121.003373,Wind Speed - Resultant,1 HOUR,1999-08-03,Knots,24,2.750000,017,0020
...,...,...,...,...,...,...,...,...,...,...,...
5150901,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-06-09,Millibars,24,1001.625000,037,0113
5150902,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-06-16,Millibars,24,999.458333,037,0113
5150903,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-08-26,Millibars,24,1003.750000,037,0113
5150904,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-09-04,Millibars,24,1001.000000,037,0113
5150905,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-12-09,Millibars,24,1012.125000,037,0113

In [28]:
aq['year'] = aq.date_local.dt.year
aq.county_code = aq.county_code.astype(int)
aq

,poc,latitude,longitude,parameter_name,sample_duration,date_local,units_of_measure,observation_count,arithmetic_mean,county_code,site_num,year
0,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-05-12,Knots,24,3.541667,11,1001,1999
1,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-08-28,Knots,24,4.041667,11,1001,1999
2,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-12,Knots,24,3.791667,11,1001,1999
3,1,39.012396,-122.092471,Wind Speed - Resultant,1 HOUR,1999-12-23,Knots,24,3.125000,11,1001,1999
4,1,38.890941,-121.003373,Wind Speed - Resultant,1 HOUR,1999-08-03,Knots,24,2.750000,17,0020,1999
...,...,...,...,...,...,...,...,...,...,...,...,...
5150901,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-06-09,Millibars,24,1001.625000,37,0113,2018
5150902,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-06-16,Millibars,24,999.458333,37,0113,2018
5150903,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-08-26,Millibars,24,1003.750000,37,0113,2018
5150904,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-09-04,Millibars,24,1001.000000,37,0113,2018
5150905,1,34.051110,-118.456360,Barometric pressure,1 HOUR,2018-12-09,Millibars,24,1012.125000,37,0113,2018

In [29]:
# small_aq = aq[(aq.year==2018)]
# small_aq

In [30]:
# small_aq['sample_duration'] = pd.to_numeric(small_aq['sample_duration'].str.extract('(\d+)', expand=False), errors='coerce').astype(pd.Int64Dtype())
# small_aq

In [31]:
# small_aq.info()

In [32]:
# piv_saq = small_aq.pivot_table(index=['date_local','county_code'],columns='parameter_name',
#                 values=['arithmetic_mean']).reset_index()
# piv_saq

In [33]:
# small_fpt.discovery_date = small_fpt.discovery_date.astype('datetime64[ns]')
# small_fpt

In [34]:
# piv_saq.columns

In [35]:
# small_ca = pd.merge(left=small_fpt,right=piv_saq,how='left',left_on=['discovery_date','county_code'],right_on=[('date_local',''),('county_code','')])
# small_ca

In [36]:
# small_ca.columns.to_list()

In [37]:
# small_ca.columns = [
#     'fire_year',
#     'date',
#     'time',
#     'cause_class',
#     'cause',
#     'fire_size',
#     'fire_size_class',
#     'lat',
#     'long',
#     'fips_code',
#     'county',
#     'county_code1',
#     'measurement_year',
#     'tree_county_code',
#     'latitude_y',
#     'longitude_y',
#     'elevation',
#     'trees_per_acre',
#     'water_on_plot',
#     'species',
#     'species_group',
#     'height',
#     'diameter',
#     'tree_alive',
#     'invasive_sampling',
#     'date_local',
#     'county_code2',
#     'bp_mean',
#     'co_mean',
#     'dp_mean',
#     'temp_mean',
#     'humidity_mean',
#     'wind_direction_mean',
#     'wind_speed_mean']

In [38]:
# small_ca = small_ca[[
#     'date',
#     'time',
#     'cause_class',
#     'cause',
#     'fire_size',
#     'fire_size_class',
#     'lat',
#     'long',
#     'elevation',
#     'county',
#     'trees_per_acre',
#     'water_on_plot',
#     'species',
#     'species_group',
#     'height',
#     'diameter',
#     'tree_alive',
#     'invasive_sampling',
#     'co_mean',
#     'temp_mean',
#     'humidity_mean',
#     'wind_direction_mean',
#     'wind_speed_mean']]
# small_ca.head()

In [39]:
# # Drop rows with missing data across all columns
# small_ca = small_ca.dropna()
# small_ca

In [40]:
# # map easy categorical values to 1 and 0
# small_ca.tree_alive = small_ca.tree_alive.map({'Live tree':1,'Dead tree':0})
# small_ca.invasive_sampling = small_ca.invasive_sampling.map({'Invasive plant data collected on all accessible land conditions':1,'Not collecting invasive plant data':0})
# small_ca

In [41]:
# small_ca.to_csv('ca_fire2018.csv',index=False)

In [42]:
fpt = None
for year in range(1997,2019):
    # fire
    sm_fire = fire[fire.fire_year==year]
    # tree
    sm_pt = pt[pt.measurement_year==year]
    sm_pt = sm_pt.dropna()
    # fire tree combine
    sm_fpt = pd.merge(left=sm_fire,right=sm_pt,how='right',left_on='county_code',right_on='tree_county_code')
    fpt = sm_fpt if fpt is None else pd.concat([fpt,sm_fpt],ignore_index=True)
fpt.discovery_date = fpt.discovery_date.astype('datetime64[ns]')
fpt

,fire_year,discovery_date,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude_x,longitude_x,fips_code,...,longitude_y,elevation,trees_per_acre_unadjusted,water_on_plot_code_name,species_common_name,species_group_code_name,total_height,current_diameter,tree_status_code_name,invasive_sampling_status_code_name
0,2001.0,2001-02-02,1315,Human,Debris and open burning,0.10,A,37.485500,-118.332900,06051,...,-118.257523,9900,6.018046,None - no water sources within the accessible ...,limber pine,Other western softwoods,37,12.6,Live tree,Invasive plant data collected on all accessibl...
1,2001.0,2001-05-24,1359,Natural,Natural,0.30,B,38.123000,-118.917100,06051,...,-118.257523,9900,6.018046,None - no water sources within the accessible ...,limber pine,Other western softwoods,37,12.6,Live tree,Invasive plant data collected on all accessibl...
2,2001.0,2001-07-02,1500,Natural,Natural,75.00,C,37.902200,-118.876200,06051,...,-118.257523,9900,6.018046,None - no water sources within the accessible ...,limber pine,Other western softwoods,37,12.6,Live tree,Invasive plant data collected on all accessibl...
3,2001.0,2001-07-02,1650,Natural,Natural,5.00,B,38.118500,-119.052900,06051,...,-118.257523,9900,6.018046,None - no water sources within the accessible ...,limber pine,Other western softwoods,37,12.6,Live tree,Invasive plant data collected on all accessibl...
4,2001.0,2001-07-02,1715,Natural,Natural,0.10,A,38.311600,-119.011000,06051,...,-118.257523,9900,6.018046,None - no water sources within the accessible ...,limber pine,Other western softwoods,37,12.6,Live tree,Invasive plant data collected on all accessibl...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43825605,2018.0,2018-06-27,0916,Missing data/not specified/undetermined,Missing data/not specified/undetermined,0.82,B,37.473869,-119.843090,06043,...,-119.546165,8700,0.999188,None - no water sources within the accessible ...,western white pine,Western white pine,94,29.4,Live tree,Not collecting invasive plant data
43825606,2018.0,2018-09-01,2242,Missing data/not specified/undetermined,Missing data/not specified/undetermined,0.10,A,37.460468,-119.878765,06043,...,-119.546165,8700,0.999188,None - no water sources within the accessible ...,western white pine,Western white pine,94,29.4,Live tree,Not collecting invasive plant data
43825607,2018.0,2018-11-18,1327,Missing data/not specified/undetermined,Missing data/not specified/undetermined,1.00,B,37.585661,-120.287601,06043,...,-119.546165,8700,0.999188,None - no water sources within the accessible ...,western white pine,Western white pine,94,29.4,Live tree,Not collecting invasive plant data
43825608,2018.0,2018-06-12,0302,Missing data/not specified/undetermined,Missing data/not specified/undetermined,0.02,A,37.478067,-119.976529,06043,...,-119.546165,8700,0.999188,None - no water sources within the accessible ...,western white pine,Western white pine,94,29.4,Live tree,Not collecting invasive plant data
43825609,2018.0,2018-09-04,1440,Missing data/not specified/undetermined,Missing data/not specified/undetermined,0.02,A,37.744444,-120.130000,06043,...,-119.546165,8700,0.999188,None - no water sources within the accessible ...,western white pine,Western white pine,94,29.4,Live tree,Not collecting invasive plant data

In [43]:
caq = None
for year in range(1997,2019):
    # air quality
    sm_aq = aq[(aq.year==year)]
    # pivot so row is each county on date has mean of parameters
    piv_aq = sm_aq.pivot_table(index=['date_local','county_code'],columns='parameter_name',
                    values=['arithmetic_mean']).reset_index()
    caq = piv_aq if caq is None else pd.concat([caq,piv_aq],ignore_index=True)
caq

               date_local county_code     arithmetic_mean                  \
parameter_name                        Barometric pressure Carbon monoxide
0              1997-01-01           1                 NaN        0.249759
1              1997-01-01           5                 NaN        0.131884
2              1997-01-01           7                 NaN        0.153257
3              1997-01-01           9                 NaN        0.122584
4              1997-01-01          11                 NaN             NaN
...                   ...         ...                 ...             ...
381648         2018-12-31         101                 NaN             NaN
381649         2018-12-31         107         1002.147917             NaN
381650         2018-12-31         109                 NaN             NaN
381651         2018-12-31         111          979.208333             NaN
381652         2018-12-31         113                 NaN             NaN

                                                                 \
parameter_name Dew Point Outdoor Temperature Relative Humidity
0                    NaN                 NaN                NaN
1                    NaN           61.166667                NaN
2                    NaN           60.750000          97.062500
3                    NaN           69.875000                NaN
4                    NaN           61.375000                NaN
...                  ...                 ...                ...
381648               NaN           44.420833          45.100000
381649               NaN           41.589583          77.058333
381650               NaN           40.920833          53.462500
381651               NaN           50.256944          46.937500
381652               NaN           46.820833          49.400000


parameter_name Wind Direction - Resultant Wind Speed - Resultant
0                                     NaN                    NaN
1                              154.500000               7.666667
2                              166.111111               9.152778
3                              134.541667              10.125000
4                              162.104166              14.312500
...                                   ...                    ...
381648                         320.000000               6.225000
381649                         140.275000               2.414583
381650                         186.666667               1.662500
381651                          91.923611               6.345833
381652                         335.125000              14.983333

[381653 rows x 9 columns]

In [44]:
# air quality fire tree combine
ca = pd.merge(left=fpt,right=caq,how='left',left_on=['discovery_date','county_code'],right_on=[('date_local',''),('county_code','')])

/var/folders/ml/8_q6055n29vf0c36kmj6w1900000gn/T/ipykernel_88147/3806272112.py:2: FutureWarning: merging between different levels is deprecated and will be removed in a future version. (1 levels on the left, 2 on the right)
  ca = pd.merge(left=fpt,right=caq,how='left',left_on=['discovery_date','county_code'],right_on=[('date_local',''),('county_code','')])

In [45]:
ca.head()

,fire_year,discovery_date,discovery_time,nwcg_cause_classification,nwcg_general_cause,fire_size,fire_size_class,latitude_x,longitude_x,fips_code,...,invasive_sampling_status_code_name,"(date_local, )","(county_code, )","(arithmetic_mean, Barometric pressure)","(arithmetic_mean, Carbon monoxide)","(arithmetic_mean, Dew Point)","(arithmetic_mean, Outdoor Temperature)","(arithmetic_mean, Relative Humidity )","(arithmetic_mean, Wind Direction - Resultant)","(arithmetic_mean, Wind Speed - Resultant)"
0,2001.0,2001-02-02,1315,Human,Debris and open burning,0.1,A,37.4855,-118.3329,06051,...,Invasive plant data collected on all accessibl...,2001-02-02,51.0,1027.375000,0.587500,NaN,33.783333,NaN,NaN,NaN
1,2001.0,2001-05-24,1359,Natural,Natural,0.3,B,38.1230,-118.9171,06051,...,Invasive plant data collected on all accessibl...,2001-05-24,51.0,1023.833333,0.272282,NaN,65.858333,2.916667,NaN,NaN
2,2001.0,2001-07-02,1500,Natural,Natural,75.0,C,37.9022,-118.8762,06051,...,Invasive plant data collected on all accessibl...,2001-07-02,51.0,1025.125000,NaN,NaN,72.908333,1.708333,NaN,NaN
3,2001.0,2001-07-02,1650,Natural,Natural,5.0,B,38.1185,-119.0529,06051,...,Invasive plant data collected on all accessibl...,2001-07-02,51.0,1025.125000,NaN,NaN,72.908333,1.708333,NaN,NaN
4,2001.0,2001-07-02,1715,Natural,Natural,0.1,A,38.3116,-119.0110,06051,...,Invasive plant data collected on all accessibl...,2001-07-02,51.0,1025.125000,NaN,NaN,72.908333,1.708333,NaN,NaN

In [46]:
ca.columns

Index([                                      'fire_year',
                                        'discovery_date',
                                        'discovery_time',
                             'nwcg_cause_classification',
                                    'nwcg_general_cause',
                                             'fire_size',
                                       'fire_size_class',
                                            'latitude_x',
                                           'longitude_x',
                                             'fips_code',
                                             'fips_name',
                                           'county_code',
                                      'measurement_year',
                                      'tree_county_code',
                                            'latitude_y',
                                           'longitude_y',
                                             'elevation',
                             'trees_per_acre_unadjusted',
                               'water_on_plot_code_name',
                                   'species_common_name',
                               'species_group_code_name',
                                          'total_height',
                                      'current_diameter',
                                 'tree_status_code_name',
                    'invasive_sampling_status_code_name',
                                      ('date_local', ''),
                                     ('county_code', ''),
              ('arithmetic_mean', 'Barometric pressure'),
                  ('arithmetic_mean', 'Carbon monoxide'),
                        ('arithmetic_mean', 'Dew Point'),
              ('arithmetic_mean', 'Outdoor Temperature'),
               ('arithmetic_mean', 'Relative Humidity '),
       ('arithmetic_mean', 'Wind Direction - Resultant'),
           ('arithmetic_mean', 'Wind Speed - Resultant')],
      dtype='object')

In [47]:
ca.columns = [
    'fire_year',
    'date',
    'time',
    'cause_class',
    'cause',
    'fire_size',
    'fire_size_class',
    'lat',
    'long',
    'fips_code',
    'county',
    'county_code1',
    'measurement_year',
    'tree_county_code',
    'latitude_y',
    'longitude_y',
    'elevation',
    'trees_per_acre',
    'water_on_plot',
    'species',
    'species_group',
    'height',
    'diameter',
    'tree_alive',
    'invasive_sampling',
    'date_local',
    'county_code2',
    'bp_mean',
    'co_mean',
    'dp_mean',
    'temp_mean',
    'humidity_mean',
    'wind_direction_mean',
    'wind_speed_mean']
ca = ca[[
    'date',
    'time',
    'cause_class',
    'cause',
    'fire_size',
    'fire_size_class',
    'lat',
    'long',
    'elevation',
    'county',
    'trees_per_acre',
    'water_on_plot',
    'species',
    'species_group',
    'height',
    'diameter',
    'tree_alive',
    'invasive_sampling',
    'co_mean',
    'temp_mean',
    'humidity_mean',
    'wind_direction_mean',
    'wind_speed_mean']]

In [48]:
ca.isnull().sum()

date                        574
time                      73682
cause_class                 574
cause                       574
fire_size                   574
fire_size_class             574
lat                         574
long                        574
elevation                     0
county                      574
trees_per_acre                0
water_on_plot                 0
species                       0
species_group                 0
height                        0
diameter                      0
tree_alive                    0
invasive_sampling             0
co_mean                27614377
temp_mean              18502237
humidity_mean          22246284
wind_direction_mean    20839382
wind_speed_mean        20756342
dtype: int64

In [57]:
# Drop rows with missing data
# ca[(ca.co_mean.notna())&(ca.wind_speed_mean.notna())&(ca.humidity_mean.notna())&(ca.wind_direction_mean.notna())&(ca.time.notna())].isnull().sum()
ca = ca[(ca.co_mean.notna())&(ca.wind_speed_mean.notna())&(ca.humidity_mean.notna())&(ca.wind_direction_mean.notna())&(ca.time.notna())]
ca.shape

(9947589, 23)

In [58]:
# map easy categorical values to 1 and 0
ca.tree_alive = ca.tree_alive.map({'Live tree':1,'Dead tree':0})
ca.invasive_sampling = ca.invasive_sampling.map({'Invasive plant data collected on all accessible land conditions':1,'Not collecting invasive plant data':0})
ca.sample(5)

,date,time,cause_class,cause,fire_size,fire_size_class,lat,long,elevation,county,...,species_group,height,diameter,tree_alive,invasive_sampling,co_mean,temp_mean,humidity_mean,wind_direction_mean,wind_speed_mean
12547696,2006-01-02,0022,Human,Missing data/not specified/undetermined,0.10,A,33.561944,-116.156111,500,Riverside County,...,Woodland hardwoods,27,28.000000,1,0,0.174249,54.225544,89.237923,207.320632,4.954811
42872513,2018-05-23,1506,Human,Debris and open burning,0.01,A,36.729522,-119.657563,4500,Fresno County,...,Incense-cedar,27,6.700000,1,1,0.161360,69.403646,59.547222,288.656250,4.548437
8124910,2005-12-01,2223,Missing data/not specified/undetermined,Missing data/not specified/undetermined,0.10,A,35.368818,-118.929382,5500,Kern County,...,Ponderosa and Jeffrey pines,56,16.400000,1,1,0.643730,59.723958,66.635416,189.700000,4.408333
38313172,2017-08-29,2140,Human,Arson/incendiarism,1.00,B,36.327399,-120.211799,9500,Fresno County,...,Western white pine,110,42.400002,0,1,0.264526,91.294643,42.686111,231.766667,3.599479
7636018,2005-08-20,1721,Human,Arson/incendiarism,1.50,B,39.763056,-121.741111,3900,Butte County,...,Sugar pine,75,14.100000,0,1,0.327627,76.027778,46.263889,169.513889,2.041667

In [59]:
ca.to_csv('ca_fire.csv',index=False)